# Generated by Django 3.1.3 on 2020-12-05 12:21

import decrypt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_hidden', models.ImageField(blank=True, null=True, upload_to=decrypt.models.user_directory_path)),
                ('used_to_hide', models.ImageField(blank=True, null=True, upload_to=decrypt.models.user_directory_path)),
                ('encrypted_picture', models.ImageField(upload_to=decrypt.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decryptImages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
